# syntax=docker/dockerfile:1

FROM amazonlinux:2023 AS builder

RUN dnf install -y rust cargo gcc openssl-devel pkgconfig && dnf clean all
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

FROM amazonlinux:2023
RUN dnf install -y ca-certificates libgcc libstdc++ && dnf clean all
WORKDIR /app
COPY --from=builder /app/target/release/http-in-enclave /usr/local/bin/http-in-enclave
EXPOSE 3000
ENV PORT=3000
CMD ["/usr/local/bin/http-in-enclave"]

